#!/usr/bin/env bash
#
# Note: This script uses parallel Giz (pigz)
#       to decompress the gz files. If you do
#       not have it installed, perform the following
#
#  sudo add-apt-repository universe
#  sudo apt-get install pigz
# 
# Usage:
#
#   Edit the four varilables below and then
#
#   source helper
#   
#   Execute the convert command
#
set -e 

# Set the base variables
CSV_DIR="/data/wspr/raw/csv"
PARQUET_DIR="/data/wspr/raw/parquet"
YEAR="2020"
MONTH="02"

# -- no edits needed below this line --#
clear
CORES=$(nproc)

echo 'Setting Process Variables'
echo ''
rm -f $infile > /dev/null 2>&1
gzfile="$CSV_DIR/wsprspots-$YEAR-$MONTH.csv.gz"

echo "Decompress ...: $gzfile"
pigz -dkf "$CSV_DIR/wsprspots-$YEAR-$MONTH.csv.gz"

export infile="$CSV_DIR/wsprspots-$YEAR-$MONTH.csv"
export outdir="$PARQUET_DIR/$YEAR/$MONTH"

echo "In File ......: $infile"
echo "Out Dir ......: $outdir"
echo ""
echo 'Execute Cmd ..: . helper && spark-submit --master local[16] target/scala-2.12/ConvertCsvToParquet-assembly-1.0.jar $infile $outdir'
